fix: k8s cluster and nodepool should fail if state failed
ionos-cloud/terraform-provider-ionoscloud pull request #593
Opened 2024-07-01 13:28 UTC by cristiGuranIonos

## What does this fix or implement?

## Checklist

- [ ] PR name added as appropriate (e.g. `feat:`/`fix:`/`doc:`/`test:`/`refactor:`)
- [ ] Tests added or updated
- [ ] Documentation updated
- [ ] Changelog updated and version incremented (label: upcoming release)
- [ ] Github Issue linked if any
- [ ] Jira task updated

2024-07-01 14:58 UTC, digna-ionos commented on ionoscloud/resource_k8s_cluster.go
> +	if resource.Metadata == nil || resource.Metadata.State == nil {
I think if the Metadata is nil it will try to check also the Metadata.State if you use OR

2024-07-02 09:56 UTC, adeatcu-ionos requested changes

2024-07-02 09:56 UTC, adeatcu-ionos commented on ionoscloud/resource_k8s_cluster.go
> +			return false, fmt.Errorf("error while deleting k8s cluster %s, state %s", *cluster.Id, *cluster.Metadata.State)
@cristiGuranIonos 
```suggestion
			return false, fmt.Errorf("error while checking if k8s cluster is deleted properly, cluster ID: %s, state: %s", *cluster.Id, *cluster.Metadata.State)
```

2024-07-02 09:56 UTC, adeatcu-ionos commented on ionoscloud/resource_k8s_node_pool.go
> +			return false, fmt.Errorf("error while deleting k8s nodepool %s, state %s", *resource.Id, *resource.Metadata.State)
@cristiGuranIonos 
```suggestion
			return false, fmt.Errorf("error while checking if k8s nodepool is properly deleted, nodepool ID: %s, state: %s", *resource.Id, *resource.Metadata.State)
```

2024-07-02 11:00 UTC, adeatcu-ionos approved these changes

2024-07-03 07:32 UTC, merged